In [1]:
import numpy as np
print(np.arange(0, 10)[:, np.newaxis])

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [8]:
x= ([np.arange(0, 10)],[np.arange(10,20)])
print(x)
print(x[np.newaxis, :])

([array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])], [array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])])


TypeError: tuple indices must be integers or slices, not tuple

In [9]:
import numpy as np
x=np.arange(4)
print(x)#初始的一维数组
print(x[np.newaxis,:])#得到的二维数组
print(x[:,np.newaxis])#得到的另一个二维数组

[0 1 2 3]
[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


In [12]:
x=np.random.rand(10,2)
print(x.shape)#初始的二维数组的规模
diff=x[:,np.newaxis,:]-x[np.newaxis,:,:]
print(x[:,np.newaxis,:].shape)#三维数组的规模
print(diff.shape)#最后的数组的规模


(10, 2)
(10, 1, 2)
(1, 10, 2)


In [1]:
import os
print(os.sep)

\


In [12]:
import torch
device = torch.device("cpu" if not torch.cuda.is_available() else "cuda:0")
print(device)


cuda:0
